version: 2.1

jobs:
  cx-build-pipeline:
    machine: true
    resource_class: dasmlab/docker
    steps:
      - checkout

      # Debug/Learn - Print all the Circle CI var
      - run:
          name: Print all CircleCI Env Vars
          command: env | grep -i CIRCLE

      # Set ENV Vars (since envrionment doesnt expand sub vars)
      - run:
          name: Set env vars for this job
          command: |

            export SHORT_SHA=${CIRCLE_SHA1:0:8}" 
            export NETWORK_NAME=dasmlab-circleci-net-${CIRCLE_SHA1:0:8}" 
            export IMAGE_TAG=mcpsa-list-service:latest" 
            export CONTAINER_NAME=mcpsa-list-service-${SHORT_SHA}"

            echo "export SHORT_SHA=${CIRCLE_SHA1:0:8}" >> $BASH_ENV
            echo "export NETWORK_NAME=dasmlab-circlenet-${CIRCLE_SHA1:0:8}" >> $BASH_ENV
            echo "export IMAGE_TAG=mcpsa-list-service:latest" >> $BASH_ENV
            echo "export CONTAINER_NAME=mcpsa-list-service-${CIRCLE_SHA1:0:8}" >> $BASH_ENV
            echo "NETWORK_NAME=$NETWORK_NAME"
            echo "IMAGE_TAG=$IMAGE_TAG"
            echo "CONTAINER_NAME=$CONTAINER_NAME"
            echo "SHORT_SHA=$SHORT_SHA"

      # Build Phase - Create our Target Container
      - run:
          name: Build Docker image
          command: |
            echo "ENV"
            env
            echo "END ENV"
            sudo docker build -t ${IMAGE_TAG} .

      # Run Phase - Create Network, start container and Healtcheck
      - run:
          name: Start up Target Build in Isolated Network and Healthcheck
          command: |
            echo "ENV"
            env
            echo "ENV END"
            sudo docker network create ${NETWORK_NAME}
            sudo docker rm -f ${CONTAINER_NAME} 2>/dev/null || true
            sudo docker run -d --name ${CONTAINER_NAME} --network ${NETWORK_NAME} ${IMAGE_TAG}
            # Simple sleep to wait for start, can be improved! ;)
            sleep 5
            sudo docker exec ${CONTAINER_NAME} curl -f http://localhost:8000/isalive || (echo "Basic Healthcheck Failed" && exit 1)

      # Secure Phase: Start up dasmlab Security Suite and Scan/Evaluate Target Image
      - run:
          name: Run Security Suite (dasmlab)
          command: |
            echo "ENV"
            env
            echo "END ENV"
            echo "Starting Security Suite Instance in ${NETWORK_NAME} network"
            #sudo docker run -d --rm --network ${NETWORK_NAME} ghcr.io/dasmlab/security-suite:latest
            exit 0

      # Testing Phase: Start up dasmlab Testing Suite and Validate/Test Target Image
      - run:
          name: Run Testing Suite (dasmlab)
          command: |
            echo "ENV"
            env
            echo "END ENV"
            echo "Starting Testing Suite Instance in ${NETWORK_NAME} network"
            #sudo docker run -rm --network ${NETWORK_NAME} ghcr.io/dasmlab/testing-suite:latest
            exit 0

      # Publish Phase: Push to GHCR 
      - run:
          name: Publish Image to GHCR
          command: |
            TAG="ghcr.io/dasmlab/mcp-server-agent-list-service:${CIRCLE_SHA1:0:8}"
            #            echo "${GHCR_PAT}" > /tmp/ghcr_pat.txt
            #echo "${GHCR_PAT}" | sudo -E docker login ghcr.io -u git --password-stdin
            #sudo docker login ghcr.io -u git --password-stdin < /tmp/ghcr_pat.txt
            #rm /tmp/ghcr_pat.txt
            sudo docker tag ${IMAGE_TAG} ${TAG}
            sudo docker push ${TAG}

      # Teardown
      - run:
          name: Cleanup containers and network
          command: |
            sudo docker rm -f ${CONTAINER_NAME} || true
            sudo docker network rm ${NETWORK_NAME} || true

      # Save IMAGE_TAG for Downstream WOrkflows
      - run:
          name: Save IMAGE_TAG for downstream Workflows
          command: |
            echo "ghcr.io/dasmlab/mcp-server-agent-list-service:${CIRCLE_SHA1:0:8}" > image_tag.txt
      - persist_to_workspace:
          root: .
          paths:
            - image_tag.txt

  # - Stage up a Production AWS Cluster, VPC and setup
  setup-prod-aws:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Terraform Init/Apply
          command: |
            cd infra/aws
            terraform init
            terraform apply -auto-approve

  # Stage the Appliation + Security And Testing to Staging Cluster (known KUBECONFIG)
  cx-staging-pipeline:
    machine: true
    resource_class: dasmlab/default
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: Load IMAGE_TAG from upstream workflows
          command: |
            export IMAGE_TAG=$(cat image_tag.txt)
            echo "Deploying $IMAGE_TAG to STAGING K8s Cluster"
            # Substitue IMAGE_TAG in your manifest
            envsubst < k8s_envelope/mcpsa-list-service_deploy.yaml > deploy.yaml
            # Setup K8s configuration path
            export KUBECONFIG=/staging.kubeconfig
            # Deploy our new manifest
            kubectl apply -f deploy.yaml
      - run:
          name: Deploy Security and Testing Suite 
          command: |
            # Example: deploy manifests for security and testing suites
            kubectl apply -f k8s_envelope/security_suite.yaml
            kubectl apply -f k8s_envelope/testing_suite.yaml
            # Add wait/checks here later


      
  cx-production-pipeline:
    machine: true
    resource_class: dasmlab/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Load IMAGE_TAG From upstream build pipeline
          command: |
            export IMAGE_TAG=$(cat image_tag.txt)
            echo "Deploying $IMAGE_TAG to PRODUCTION K8s (AWS)"
            #Substitute in IMAGE_TAG in manifest
            envsubst < k8s_envelope/mcpsa-list-service_deploy.yaml > deploy.yaml
            # Setup KUBECONFIG or authenticate via previous step (Terraform output)?)
            export KUBECONFIG=/production.kubeconfig
      # Security and Testing Suite Deployment
      - run:
          name: Deploy Security Suite and Test Suite
          command: |
            kubectl apply -f k8s_envelope/security-suite.yaml
            kubectl apply -f k8s_envelope/testing-suite.yaml

          # add waits and checks later


workflows:
  build-target:
    jobs:
      - cx-pipeline
  staging-pipeline:
    jobs:
      - cx-pipeline
      - cx-staging:
          requires:
            - cx-pipeline
          filters:
            branches:
              only: staging

  production-pipeline:
    jobs:
      - cx-pipeline
      - setup-prod-aws:
          requires:
            - cx-pipeline
          filters:
            branches:
              only: prod
      - cx-production:
          requires:
            - setup-prod-aws
          filters:
            branches:
              only: prod
