version: 2.1

jobs:
  docker-build:
    machine: true
    resource_class: dasmlab/docker
    steps:
      - checkout
      - run:
          name: Ensure docker group exists with GID 999 
          command: |
            if ! grep -q "^docker:" /etc/group; then
               echo "docker:x:999:circleci" | sudo tee -a /etc/group
            fi
            sudo usermod -aG docker circleci || true
            id 
            groups
            ls -l /var/run/docker.sock
      - run:
          name: Build Docker image
          command: |
            docker build -t test:latest .

workflows:
  build-and-test:
    jobs:
      - docker-build

