version: 2.1

jobs:
  docker-build:
    machine: true
    resource_class: dasmlab/docker
    steps:
      - checkout
      - run: id
      - run: groups
      - run: ls -l /var/run/docker.sock
      - run:
          name: Build Docker image
          command: |
            docker build -t test:latest .

workflows:
  build-and-test:
    jobs:
      - docker-build

