version: 2.1

jobs:
  build-and-push:
    docker:
      - image: quay.io/buildah/stable
    environment:
      IMAGE_TAG: "${CIRCLE_SHA1:0:8}"
    steps:
      - checkout
      - run:
          name: Login to GHCR
          command: |
            buildah login -u $DOCKER_USERNAME -p $DASMLAB_GHCR_PAT ghcr.io
      - run:
          name: Build Container Image
          command: |
            export STORAGE_DRIVER=vfs
            buildah --storage-driver vfs bud -t ghcr.io/dasmlab/mcp-server-agent-list-service:${IMAGE_TAG} .
      - run:
          name: Push Image
          command: |
            buildah push ghcr.io/dasmlab/mcp-server-agent-list-service:${IMAGE_TAG}

workflows:
  build-and-push:
    jobs:
      - build-and-push

