version: 2.1

orbs:
  kaniko: crispy-collective/kaniko@1.2.2

workflows:
  build-and-push:
    jobs:
      - kaniko/build:
          dockerfile: Dockerfile
          context: .
          registry: ghcr.io
          repo: dasmlab/mcp-server-agent-list-service
          tag: << pipeline.git.revision >>

