version: 2.1

jobs:
  build:
    docker:
      - image: test-build-image
    resource_class: dasmlab/Docker
    steps:
      - checkout
      - run: docker version

workflows:
  build-and-push:
    jobs:
      - build