version: 2.1

executors:
  k8s-agent:
    docker:
      - image: gcr.io/kaniko-project/executor:latest  # Just use the Kaniko image directly

jobs:
  build-and-push:
    executor: k8s-agent
    environment:
      IMAGE_TAG: "${CIRCLE_SHA1:0:8}"
    steps:
      - checkout

      - run:
          name: Set Build Metadata
          command: |
            echo "export COMMIT_ID=$(git rev-parse --short HEAD)" >> $BASH_ENV
            echo "export VERSION_TAG=v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $BASH_ENV

      - run:
          name: Kaniko Build and Push
          command: |
            mkdir -p /kaniko/.docker
            echo "{\"auths\":{\"${DOCKER_REGISTRY}\":{\"username\":\"${DOCKER_USER}\",\"password\":\"${DASMLAB_GHCR_PAT}\"}}}" > /kaniko/.docker/config.json
            /kaniko/executor --context $PWD --dockerfile $PWD/Dockerfile --destination ${DOCKER_REGISTRY}/dasmlab-home:${IMAGE_TAG} --cache=true

