version: 2.1

jobs:
  cx-pipeline:
    machine: true
    resource_class: dasmlab/docker
    steps:
      - checkout

      # Debug/Learn - Print all the Circle CI var
      - run:
          name: Print all CircleCI Env Vars
          command: env | grep -i CIRCLE

      # Set ENV Vars (since envrionment doesnt expand sub vars)
      - run:
          name: Set env vars for this job
          command: |

            export SHORT_SHA=${CIRCLE_SHA1:0:8}" 
            export NETWORK_NAME=dasmlab-circleci-net-${CIRCLE_SHA1:0:8}" 
            export IMAGE_TAG=mcpsa-list-service:latest" 
            export CONTAINER_NAME=mcpsa-list-service-${SHORT_SHA}"

            echo "export SHORT_SHA=${CIRCLE_SHA1:0:8}" >> $BASH_ENV
            echo "export NETWORK_NAME=dasmlab-circlenet-${CIRCLE_SHA1:0:8}" >> $BASH_ENV
            echo "export IMAGE_TAG=mcpsa-list-service:latest" >> $BASH_ENV
            echo "export CONTAINER_NAME=mcpsa-list-service-${CIRCLE_SHA1:0:8}" >> $BASH_ENV
            echo "NETWORK_NAME=$NETWORK_NAME"
            echo "IMAGE_TAG=$IMAGE_TAG"
            echo "CONTAINER_NAME=$CONTAINER_NAME"
            echo "SHORT_SHA=$SHORT_SHA"

      # Build Phase - Create our Target Container
      - run:
          name: Build Docker image
          command: |
            echo "ENV"
            env
            echo "END ENV"
            sudo docker build -t ${IMAGE_TAG} .

      # Run Phase - Create Network, start container and Healtcheck
      - run:
          name: Start up Target Build in Isolated Network and Healthcheck
          command: |
            echo "ENV"
            env
            echo "ENV END"
            sudo docker network create ${NETWORK_NAME}
            sudo docker rm -f ${CONTAINER_NAME} 2>/dev/null || true
            sudo docker run -d --name ${CONTAINER_NAME} --network ${NETWORK_NAME} ${IMAGE_TAG}
            # Simple sleep to wait for start, can be improved! ;)
            sleep 5
            sudo docker exec ${CONTAINER_NAME} curl -f http://localhost:8000/isalive || (echo "Basic Healthcheck Failed" && exit 1)

      # Secure Phase: Start up dasmlab Security Suite and Scan/Evaluate Target Image
      - run:
          name: Run Security Suite (dasmlab)
          command: |
            echo "ENV"
            env
            echo "END ENV"
            echo "Starting Security Suite Instance in ${NETWORK_NAME} network"
            #sudo docker run -d --rm --network ${NETWORK_NAME} ghcr.io/dasmlab/security-suite:latest
            exit 0

      # Testing Phase: Start up dasmlab Testing Suite and Validate/Test Target Image
      - run:
          name: Run Testing Suite (dasmlab)
          command: |
            echo "ENV"
            env
            echo "END ENV"
            echo "Starting Testing Suite Instance in ${NETWORK_NAME} network"
            #sudo docker run -rm --network ${NETWORK_NAME} ghcr.io/dasmlab/testing-suite:latest
            exit 0

      # Publish Phase: Push to GHCR 
      - run:
          name: Publish Image to GHCR
          command: |
            TAG="ghcr.io/dasmlab/mcp-server-agent-list-service:${CIRCLE_SHA1:0:8}"
            sudo docker tag ${IMAGE_TAG} ${TAG}
            echo "${GHCR_PAT}" | sudo docker login ghcr.io -u git --password-stdin
            sudo docker push ${TAG}

      # Teardown
      - run:
          name: Cleanup containers and network
          command: |
            sudo docker rm -f ${CONTAINER_NAME} || true
            sudo docker network rm ${NETWORK_NAME} || true


workflows:
  build-and-test:
    jobs:
      - cx-pipeline

